language: python
python:
  - "3.6"
  - "nightly"

notifications:
  email: false

install:
  - pip install -r requirements.txt 

script:
  - pytest

after_success:
  - coverage run test_sample.py
  - coveralls